FROM php:8.4-fpm

RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libpq-dev \
    libzip-dev \
    zip \
    unzip \
    wget \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install pdo_pgsql mbstring exif pcntl bcmath gd sockets zip

RUN pecl install redis && docker-php-ext-enable redis

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && npm install -g npm

ARG user=myuser
ARG uid=1000

COPY docker/backend/php/custom.ini /usr/local/etc/php/conf.d/custom.ini
COPY docker/backend/php/www-dev.conf /usr/local/etc/php-fpm.d/zzz-dev.conf

COPY docker/backend/entrypoint.dev.sh /usr/local/bin/entrypoint.dev.sh
RUN chmod +x /usr/local/bin/entrypoint.dev.sh

RUN useradd -m -u $uid -G www-data,root -s /bin/bash $user \
    && mkdir -p /home/$user/.composer \
    && chown -R $user:$user /home/$user

WORKDIR /var/www

ENTRYPOINT ["entrypoint.dev.sh"]
CMD ["php-fpm"]
