import type { Congregation } from "./types"

export const initialCongregations: Congregation[] = [
  {
    id: "1",
    name: "Congregação Centro",
    code: "CG-001",
    church: "Igreja Central Demo",
    leader: "Diácono Pedro Alves",
    city: "São Paulo",
    state: "SP",
    members: 145,
    phone: "(11) 3333-1111",
    status: "active",
  },
  {
    id: "2",
    name: "Congregação Zona Norte",
    code: "CG-002",
    church: "Igreja Central Demo",
    leader: "Diácono Carlos Souza",
    city: "São Paulo",
    state: "SP",
    members: 98,
    phone: "(11) 3333-2222",
    status: "active",
  },
  {
    id: "3",
    name: "Congregação Zona Sul",
    code: "CG-003",
    church: "Igreja Central Demo",
    leader: "Evangelista Sandra Lima",
    city: "São Paulo",
    state: "SP",
    members: 72,
    phone: "(11) 3333-3333",
    status: "active",
  },
  {
    id: "4",
    name: "Congregação Zona Leste",
    code: "CG-004",
    church: "Igreja Central Demo",
    leader: "Diácono José Ribeiro",
    city: "São Paulo",
    state: "SP",
    members: 34,
    phone: "(11) 3333-4444",
    status: "inactive",
  },
  {
    id: "5",
    name: "Congregação Campinas Centro",
    code: "CG-005",
    church: "Igreja Central Demo",
    leader: "Evangelista Ricardo Martins",
    city: "Campinas",
    state: "SP",
    members: 165,
    phone: "(19) 3456-5555",
    status: "active",
  },
]
