import type { Member } from "./types"

export const initialMembers: Member[] = [
  {
    id: "1",
    name: "Ana Paula Ferreira",
    email: "ana.ferreira@email.com",
    phone: "(11) 98888-0001",
    church: "Igreja Central Demo",
    department: "Louvor",
    status: "active",
    joined_at: "2024-02-10",
  },
  {
    id: "2",
    name: "Beatriz Nascimento",
    email: "beatriz.nascimento@email.com",
    phone: "(11) 98888-0002",
    church: "Igreja Central Demo",
    department: "Infantil",
    status: "active",
    joined_at: "2023-11-05",
  },
  {
    id: "3",
    name: "Carlos Eduardo Souza",
    email: "carlos.souza@email.com",
    phone: "(11) 98888-0003",
    church: "Igreja Central Demo",
    department: "Diaconia",
    status: "active",
    joined_at: "2022-06-20",
  },
  {
    id: "4",
    name: "Daniela Rocha",
    email: "daniela.rocha@email.com",
    phone: "(11) 98888-0004",
    church: "Igreja Central Demo",
    department: "Jovens",
    status: "visitor",
    joined_at: "2026-06-30",
  },
  {
    id: "5",
    name: "Eduardo Lima",
    email: "eduardo.lima@email.com",
    phone: "(11) 98888-0005",
    church: "Igreja Central Demo",
    department: "Ensino",
    status: "active",
    joined_at: "2021-03-14",
  },
  {
    id: "6",
    name: "Fernanda Costa",
    email: "fernanda.costa@email.com",
    phone: "(11) 98888-0006",
    church: "Igreja Central Demo",
    department: "Louvor",
    status: "inactive",
    joined_at: "2020-09-01",
  },
  {
    id: "7",
    name: "Gabriel Martins",
    email: "gabriel.martins@email.com",
    phone: "(11) 98888-0007",
    church: "Igreja Central Demo",
    department: "Jovens",
    status: "active",
    joined_at: "2024-08-18",
  },
  {
    id: "8",
    name: "Helena Ribeiro",
    email: "helena.ribeiro@email.com",
    phone: "(11) 98888-0008",
    church: "Igreja Central Demo",
    department: "Intercessão",
    status: "active",
    joined_at: "2023-01-22",
  },
]
